USE Business_KPI_Analytics;
GO

/* =========================================================
   1. REVENUE GROWTH
   ========================================================= */
WITH monthly AS (
    SELECT
        DATEFROMPARTS(YEAR(order_date), MONTH(order_date), 1) AS month_start,
        SUM(revenue) AS revenue
    FROM stg.orders
    GROUP BY DATEFROMPARTS(YEAR(order_date), MONTH(order_date), 1)
)
SELECT
    month_start,
    revenue,
    LAG(revenue) OVER (ORDER BY month_start) AS previous_month_revenue,
    ROUND((revenue - LAG(revenue) OVER (ORDER BY month_start))
          / NULLIF(LAG(revenue) OVER (ORDER BY month_start),0) * 100.0, 2) AS revenue_growth_pct
FROM monthly
ORDER BY month_start;


/* =========================================================
   2. PROFIT MARGIN
   ========================================================= */
SELECT
    ROUND(SUM(revenue),2) AS revenue,
    ROUND(SUM(profit),2) AS profit,
    ROUND(SUM(profit) / NULLIF(SUM(revenue),0) * 100.0, 2) AS profit_margin_pct
FROM stg.orders;


/* =========================================================
   3. CUSTOMER ACQUISITION COST (CAC)
   ========================================================= */
WITH new_customers AS (
    SELECT acquisition_channel AS channel, COUNT(*) AS customers_acquired
    FROM stg.customers
    GROUP BY acquisition_channel
),
spend AS (
    SELECT channel, SUM(spend) AS marketing_spend
    FROM stg.marketing_spend
    GROUP BY channel
)
SELECT
    s.channel,
    s.marketing_spend,
    n.customers_acquired,
    ROUND(s.marketing_spend / NULLIF(n.customers_acquired,0),2) AS cac
FROM spend s
LEFT JOIN new_customers n ON s.channel = n.channel
ORDER BY cac;


/* =========================================================
   4. CUSTOMER LIFETIME VALUE (LTV)
   Practical historical proxy:
   average customer revenue over observed customer lifespan.
   ========================================================= */
WITH customer_value AS (
    SELECT
        customer_id,
        SUM(revenue) AS customer_revenue,
        COUNT(DISTINCT order_id) AS orders_count
    FROM stg.orders
    GROUP BY customer_id
)
SELECT
    ROUND(AVG(customer_revenue),2) AS avg_historical_ltv,
    ROUND(AVG(orders_count),2) AS avg_orders_per_customer
FROM customer_value;


/* =========================================================
   5. CHURN RATE
   A customer is considered churned when they have no order
   in the final 90 days of the reporting period.
   ========================================================= */
DECLARE @period_end DATE = '2025-12-31';
DECLARE @churn_cutoff DATE = DATEADD(DAY,-90,@period_end);

WITH active_start AS (
    SELECT DISTINCT customer_id
    FROM stg.orders
    WHERE order_date <= @churn_cutoff
),
active_late AS (
    SELECT DISTINCT customer_id
    FROM stg.orders
    WHERE order_date > @churn_cutoff
)
SELECT
    COUNT(*) AS customers_at_risk,
    SUM(CASE WHEN l.customer_id IS NULL THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN l.customer_id IS NULL THEN 1 ELSE 0 END)
        / NULLIF(COUNT(*),0) * 100.0, 2
    ) AS churn_rate_pct
FROM active_start s
LEFT JOIN active_late l ON s.customer_id = l.customer_id;


/* =========================================================
   6. CONVERSION RATE
   ========================================================= */
SELECT
    COUNT(*) AS sessions,
    SUM(CAST(converted AS INT)) AS conversions,
    ROUND(SUM(CAST(converted AS INT)) / NULLIF(COUNT(*),0) * 100.0, 2) AS conversion_rate_pct
FROM stg.website_sessions;


/* =========================================================
   7. AVERAGE ORDER VALUE
   ========================================================= */
SELECT
    ROUND(SUM(revenue) / NULLIF(COUNT(DISTINCT order_id),0),2) AS aov
FROM stg.orders;


/* =========================================================
   8. ROI
   ROI = (Gain - Investment) / Investment
   Here, gain is profit generated by sales.
   ========================================================= */
WITH totals AS (
    SELECT SUM(profit) AS profit FROM stg.orders
),
spend AS (
    SELECT SUM(spend) AS marketing_spend FROM stg.marketing_spend
)
SELECT
    ROUND((t.profit - s.marketing_spend) / NULLIF(s.marketing_spend,0) * 100.0, 2) AS roi_pct
FROM totals t CROSS JOIN spend s;


/* =========================================================
   9. CSAT
   Satisfied = score 4 or 5.
   ========================================================= */
SELECT
    ROUND(
        SUM(CASE WHEN csat_score >= 4 THEN 1 ELSE 0 END)
        / NULLIF(COUNT(*),0) * 100.0, 2
    ) AS csat_pct
FROM stg.customer_feedback;


/* =========================================================
   10. NPS
   Promoters = 9-10; Passives = 7-8; Detractors = 0-6.
   NPS = % Promoters - % Detractors.
   ========================================================= */
SELECT
    ROUND(
        100.0 * (
            SUM(CASE WHEN nps_score >= 9 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0)
            -
            SUM(CASE WHEN nps_score <= 6 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0)
        ), 2
    ) AS nps
FROM stg.customer_feedback;
